# -*- coding: utf-8 -*-
"""Jaquar-BOT.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16eHFyzbDI6auJUj8PHPYXWe8p-ujpW6M

### Bot Architecture
- create a dictionary for faqs
- create faqs embeddings
- create faqs for autocompletion via millisearch
---
- user response will be classified with intents.
- all questions of faq will be in one faq intent
- if faq then search faq in dictionary if not, search in embeddings
- create query embeddings and calculate similarity with predefined faq embeddings
- if similarity is higher than threshold, return faq, if not
- fallback

## Creating UI Models for Response
"""

# Firebase, Pydantic, FastAPI, Transformers, SentenceTransformer

from pydantic import BaseModel, HttpUrl, validator, AnyUrl
from typing import List, Optional, Union
import pprint
pp = pprint.PrettyPrinter(depth=8, width=120)

class Button(BaseModel):
    button_text: str
    button_value: str
    button_type: str = "default"
    button_url_redirect: Optional[HttpUrl] = None
    icon_url: Optional[HttpUrl] = None
    
    @validator('button_type')
    def validate_button_type(cls, v):
        if v not in ["default", "submit"]:
            raise ValueError('Invalid button type')
        return v

class GenericFormSchema(BaseModel):
    title:str
    value:str

class Dropdown(BaseModel):
    dropdown_items: List[GenericFormSchema]
    dropdown_value: str
    dropdown_placeholder: str

class CheckBox(BaseModel):
    checkbox_items: List[GenericFormSchema]
    checkbox_value: str
    checkbox_checked: bool = False

class RadioButton(BaseModel):
    radiobutton_items: List[GenericFormSchema]
    radiobutton_value: str
    radiobutton_checked: bool = False

class Range(BaseModel):
    range_title: str
    range_default_value: int
    range_min: int = 0
    range_max: int = 5
    range_step: float = 1.0
    range_value: str

    @validator('range_default_value', 'range_min', 'range_max', 'range_step')
    def validate_atts(cls, v, values, field):
        if field.name=="range_default_value":
            if v < 0:
                raise ValueError('Invalid default range value')
        if field.name=="range_min":
            if v < 0:
                raise ValueError('Invalid minimum range value')
        if field.name=="range_max":
            if v < 0:
                raise ValueError('Invalid maximum range value')
        if field.name=="range_step":
            if v < 0:
                raise ValueError('Invalid step value')

        if len(values)==4:
            default_value = values["range_default_value"]
            min_value = values["range_min"]
            max_value = values["range_max"]
            step = v

            if default_value < min_value or default_value > max_value or min_value > max_value:
                raise ValueError('Invalid range')
            if step <= 0:
                raise ValueError('Invalid step')
        return v
        
    

class TextInput(BaseModel):
    textinput_placeholder: str
    textinput_type: str = "default"
    textinput_value: str

    @validator('textinput_type')
    def validate_textinput_type(cls, v):
        if v not in ["default", "password", "email", "phone", "multiline"]:
            raise ValueError('Invalid text input type')
        return v

class FileUpload(BaseModel):
    file_upload_title: str
    file_upload_description: Optional[str]
    file_upload_accept: Optional[str]
    file_upload_multiple: Optional[bool] = False
    file_upload_value: str

class Form(BaseModel):
    form_title: str
    form_description: Optional[str] = None
    form_items: List[Union[Dropdown, CheckBox, RadioButton, Range, TextInput, FileUpload]]
    form_submit_button: Button

class Image(BaseModel):
    image_url: HttpUrl
    image_title: str
    image_text: Optional[str] = None

class Video(BaseModel):
    video_url: HttpUrl
    video_title: str
    video_text: Optional[str] = None

class GeneralUrl(AnyUrl):
    allowed_schemes = {'http','https','tel','mailto'}

class Url(BaseModel):
    url_title: str
    url_url: GeneralUrl
    url_text: Optional[str] = None

class ListGroup(BaseModel):
    list_items: Union[List[Button], List[GenericFormSchema]]
    list_value: str

class Label(BaseModel):
    label_body: str
    label_type: str = "default"
    label_value: Optional[str]
    
    @validator('label_type')
    def validate_text_type(cls, v):
        if v not in ["default", "rich_text"]:
            raise ValueError('Invalid text type')
        return v

class Card(BaseModel):
    card_heading: str
    card_subheading: Optional[str] = None
    card_body: str
    card_buttons: Optional[List[Button]] = None
    card_image: Optional[Image] = None
    card_video: Optional[Video] = None
    card_type: str = "default"
    
    @validator('card_type')
    def validate_card_type(cls, v):
        if v not in ["default", "image", "video"]:
            raise ValueError('Invalid card type')
        return v

class Carousel(BaseModel):
    carousel_items: Union[List[Card] , List[Url] , List[Image] , List[Video]]
    carousel_type: str = "card"
    
    @validator('carousel_type')
    def validate_carousel_type(cls, v):
        if v not in ["card", "image", "video", "url"]:
            raise ValueError('Invalid carousel type')
        return v

class ResponseElement(BaseModel):
    type: str
    element: Union[Label, Form, FileUpload, ListGroup, Carousel, Card, Url, Image, Video]

class Response(BaseModel):
    response_items: List[ResponseElement]
    context: Optional[List[str]] = None

class Intent(BaseModel):
    tag: str
    pattern: List[str]
    response: Response

# r = Range(range_title="Skill Set", range_default_value=3, range_min=1, range_max=10, range_step=1.5, range_value="skill")

"""## Jaquar"""

feedback_label = Label(label_body="Please fill up the following details to provide your feedback.", label_type="default", label_value="feedback")
feedback_name = TextInput(textinput_placeholder="Please provide your name", textinput_type="default", textinput_value="user_name")
feedback_email = TextInput(textinput_placeholder="Please provide your Email", textinput_type="email", textinput_value="user_email")
feedback_text = TextInput(textinput_placeholder="Please provide your feedback", textinput_type="multiline", textinput_value="user_feedback")
feedback_form = Form(form_title="Feedback Form", form_items=[feedback_name, feedback_email, feedback_text], form_value="contact_details", form_submit_button=Button(button_text="Submit", button_value="feedback_exit", button_type="submit"))
feedback_response = Response(response_items = [ResponseElement(type="label", element=feedback_label ), ResponseElement(type="form", element=feedback_form) ], context=["user_name","user_email","user_feedback"])
feedback_intent = Intent(tag="feedback", response=feedback_response, pattern=[ "i want to provide feedback", "feedback", "i want to share my opinions", "i want to share my experience", "i want to share my experience with you", "how can I give feedback"])

feedback_exit_label1 = Label(label_body="Thank you for your time in giving us feedback.", label_type="default", label_value="feedback_exit")
feedback_exit_label2 = Label(label_body="Would you like to continue?", label_type="default", label_value="feedback_exit")
feedback_exit_list = ListGroup(listgroup_title="Choose option", list_items=[Button(button_text="Yes", button_value="main_menu"), Button(button_text="No", button_value="exit")], list_value="choose_options")
feedback_exit_response = Response(response_items = [ResponseElement(type="label", element=feedback_exit_label1 ), ResponseElement(type="label", element=feedback_exit_label2 ), ResponseElement(type="list", element=feedback_exit_list) ])
feedback_exit_intent = Intent(tag="feedback_exit", response=feedback_exit_response, pattern=["feedback_exit","feedback exit"])
 
welcome_label1 = Label(label_body="Welcome to Jaquar - A Complete bathroom & lighting solutions brand.", label_type="default", label_value="welcome_msg")
welcome_label2 = Label(label_body="I am Jaq - Your virtual assistant. How may I help you today?", label_type="default", label_value="welcome_msg")
welcome_label3 = Label(label_body="Please select an option from the menu below.", label_type="default", label_value="welcome_msg")
welcome_list = ListGroup(listgroup_title="Choose option", list_items=[Button(button_text="Customer", button_value="Customer"), Button(button_text="Professional", button_value="Professional"), Button(button_text="Call Purchase Assistant", button_value="Call Purchase Assistant"), Button(button_text="Orientation Center Virtual Tour", button_value="center_virtual_tour", button_url_redirect="https://www.jaquar.com/en/self-tour?redirect=orientation"), Button(button_text="Customer Service", button_value="Customer Service"), Button(button_text="Dealer Location", button_value="Dealer Location"), Button(button_text="Download Our Mobile Apps", button_value="Download Our Mobile Apps"), Button(button_text="Visit Our Social Media Handles", button_value="Visit Our Social Media Handles")], list_value="choose_options")
welcome_response = Response(response_items = [ResponseElement(type="label", element=welcome_label1 ), ResponseElement(type="label", element=welcome_label2 ), ResponseElement(type="label", element=welcome_label3 ), ResponseElement(type="list", element=welcome_list) ])
welcome_intent = Intent(tag="welcome", response=welcome_response, pattern=["yo","heya","heylo","konichiwa","hi friend","hello sweatheart","hi there it's me","hei","hello","helo","hieeeeeeeeeeeee","hi bot","i said, helllllloooooo!!!!","hellio","heyho","well hello there ;)","hi again","hi folks","heeey","hlo","hello there","hello bot","hello everybody","hi?","hey there","bonjour","hii","hi","hey bot","hey bot!","hello sweet boy","hello is anybody there","yoo","halloo","hellooo","hi sara","hi pal!","hallo sara","hi im amanda anderson","hello buddy","hi there","hell9o","hey there..","greetings","hi!","hey, let's talk","helloooo","hi,","hi friends","hey ther","hi !","hallo","hey hey","hi.......","hi, bot","halo","hi hi","hi man","hello world","hiihihi","hey, sara!","heyo","ey boss","greet","hi i'm sandra hernandez","jojojo","hello, my name is charles pfeffer","hello it is me again","hellllooooooo","hey","helleo","halloooo","hola","hi mister","hieee","hello robot","hey let's talk","hello!","hey there boy","hello friend","hiii","hello hi","hello?","hey dude","howdy","hi'","heelio"])
#2
main_menu_label1 = Label(label_body="How may I help you today?", label_type="default", label_value="main_menu")
main_menu_label2 = Label(label_body="Please select an option from the menu below.", label_type="default", label_value="main_menu")
main_menu_list = ListGroup(listgroup_title="Choose option", list_items=[Button(button_text="Customer", button_value="Customer"), Button(button_text="Professional", button_value="Professional"), Button(button_text="Call Purchase Assistant", button_value="Call Purchase Assistant"), Button(button_text="Orientation Center Virtual Tour", button_value="center_virtual_tour", button_url_redirect="https://www.jaquar.com/en/self-tour?redirect=orientation"), Button(button_text="Customer Service", button_value="Customer Service"), Button(button_text="Dealer Location", button_value="Dealer Location"), Button(button_text="Download Our Mobile App", button_value="Download Our Mobile App"), Button(button_text="Visit Our Social Media Handles", button_value="Visit Our Social Media Handles")], list_value="choose_options")
main_menu_response = Response(response_items = [ResponseElement(type="label", element=main_menu_label1 ), ResponseElement(type="label", element=main_menu_label2 ), ResponseElement(type="list", element=main_menu_list) ])
main_menu_intent = Intent(tag="main_menu", response=main_menu_response, pattern=["main_menu","main menu","start menu","go back to main menu","go to main menu","initial point"])

thankyou_label = Label(label_body="My pleaure, I'm always at your service", label_type="default", label_value="thankyou")
thankyou_response = Response(response_items = [ResponseElement(type="label", element=thankyou_label )])
thankyou_intent = Intent(tag="thankyou", response=thankyou_response, pattern=["appreciate it","very good thank you","thnx","awesome service","thanks love","thank you for your help","much thanks","thanks!","great thanks","thanks a bunch for everything","many thanks","thx for your help","thank's!","thank u","thnks","thanks bot","thank you again","thx","thanks","thanks this is great news","you helped a lot thank you","i see, thanks","thank you my friend","thanks goodbye","thanks for the help!","thanks for that","thanks for your information","terrific thank you","i appreciate it","nice thank you","cool thanks","thankyou","ok thx","i appreciate your help","good thanks","it's appreciated","great, thanks","ty","thanks for your help","great thank you","alright thanks","that's appreciated","appreciate all the help","appreciate your help","amazing, thanks","ok thanks","oh thats good!","okay thank you","thanks a lot","much appreciated","tnx","ok thanks!","ok thanks sara","cheers bro","thank you sara","thnaks","alright thank you","thanks again","well thanks","i thank you","thanks you","perfect thank you","cool thank you","thanks for the help","cool, thanks","thank you and good bye","thanx","thank you","thank you anyways","cool. thank you. i really like what you're doing.","thank you so much","cool. thanks","thank you that will be all","yes thanks","thanks so much","amazing service","thanks buddy","well thank you"])

bot_challenge_label = Label(label_body="I am Jaq, Your virtual assistant. I'm here to answer your questions. How can I help you?", label_type="default", label_value="bot_challenge")
bot_challenge_list = ListGroup(listgroup_title="Choose option", list_items=[Button(button_text="Customer", button_value="Customer"), Button(button_text="Professional", button_value="Professional"), Button(button_text="Call Purchase Assistant", button_value="Call Purchase Assistant"), Button(button_text="Orientation Center Virtual Tour", button_value="center_virtual_tour", button_url_redirect="https://www.jaquar.com/en/self-tour?redirect=orientation"), Button(button_text="Customer Service", button_value="Customer Service"), Button(button_text="Dealer Location", button_value="Dealer Location"), Button(button_text="Download Our Mobile Apps", button_value="Download Our Mobile Apps"), Button(button_text="Visit Our Social Media Handles", button_value="Visit Our Social Media Handles")], list_value="choose_options")
bot_challenge_response = Response(response_items = [ResponseElement(type="label", element=bot_challenge_label ), ResponseElement(type="list", element=bot_challenge_list) ])
bot_challenge_intent = Intent(tag="bot_challenge", response=bot_challenge_response, pattern=["are you human?","am i talking to a bot?","you are not real","am i speaking to an ai?","are you a real human?","are you artificial intelligence","you are a real person","who are you?","i'm obviously talking to a computer","you are chatbot","you're a human, right?","what are you?","are you sure that you're a bot?","you are a bot","i think you are real","is this a human?","is this a bot?","you are real","who am i talking to?","am i chatting with a human?","you're a robot","am i talking to a human?","are you real?","are you a bot","are you robot","you are not fake","are you a real bot?","are you a program","are you artificial","are you an ai?","you're a bot aren't you?","are you a bot?","you are very real","bot or human?","i suppose you're real","i guess you're real","are you virtual?","are you a chatbot","are you a chatbot or human?","aren't you a bot","are you a human or a bot?","you are a chatbot","am i talking to an actual person?","are you a rasa bot?","are you just a bot","you're a chatbot","human or bot?","are you a real human","you are so real","am i taking to bot","why are you here","are you really a bot","are you a chatbot?","are you even a real person?","are you a robot?","are you real","are you a robot","are you a human?","are you ai","are you a real person?","are you a real person"])

customer_label = Label(label_body="Please select an option from the menu below.", label_type="default", label_value="customer")
customer_list = ListGroup(listgroup_title="Choose option", list_items=[Button(button_text="Bathroom Products", button_value="Bathroom Products"), Button(button_text="Lighting Products", button_value="Lighting Products"), Button(button_text="Call Purchase Assistant", button_value="Call Purchase Assistant"), Button(button_text="Orientation Center Virtual Tour", button_value="center_virtual_tour", button_url_redirect="https://www.jaquar.com/en/self-tour?redirect=orientation"), Button(button_text="Dealer Location", button_value="Dealer Location"), Button(button_text="Download Catalogue", button_value="download_customer_catalogue"), Button(button_text="Customer Service", button_value="customer_service"), Button(button_text="Download Our Mobile App", button_value="Download Our Mobile App"), Button(button_text="Visit Our Social Media Handles", button_value="social_media"), Button(button_text="Go back to Previous Menu", button_value="previous_menu"), Button(button_text="Main Menu", button_value="Main Menu")], list_value="choose_options")
customer_response = Response(response_items = [ResponseElement(type="label", element=customer_label ), ResponseElement(type="list", element=customer_list) ])
customer_intent = Intent(tag="customer", response=customer_response, pattern=["Customer", "i am a customer"])

bathroom_products_label = Label(label_body="Jaquar is into complete bathroom solutions. Please select from the menu given below", label_type="default", label_value="bathroom_products")
new_arrival_card = Card(card_heading="New Arrivals", card_body="New arrivals to our ever-growing range of luxury bathroom products", card_type="image", card_image=Image(image_url="https://www.jaquar.com/images/thumbs/0024607_laguna-faucets_400.jpeg", image_title="New Arrivals"), card_buttons=[Button(button_text="Know More", button_url_redirect="https://www.jaquar.com/en/new-arrival", button_value="after_redirect")])
faucets_card = Card(card_heading="Faucets", card_body="A great cleansing experience with their high-quality performance and eye-catching designs.", card_type="image", card_image=Image(image_url="https://www.jaquar.com/images/thumbs/0012246_faucets_400.jpeg", image_title="Faucets"), card_buttons=[Button(button_text="Know More", button_url_redirect="https://www.jaquar.com/en/faucets", button_value="after_redirect")])
showers_card = Card(card_heading="Showers", card_body="Jaquar Bathroom showers are designed to deliver a range of experiences to let you have a shower of your choice every time.", card_type="image", card_image=Image(image_url="https://www.jaquar.com/images/thumbs/0006931_hydrolite-showers_400.jpeg", image_title="Showers"), card_buttons=[Button(button_text="Know More", button_url_redirect="https://www.jaquar.com/en/showers", button_value="after_redirect")])
sanitaryware_card = Card(card_heading="Sanitaryware", card_body="Jaquar sanitary items have been designed in a unique way that makes sure to go beyond just a sense of comfort.", card_type="image", card_image=Image(image_url="https://www.jaquar.com/images/thumbs/0040179_sanitaryware_400.jpeg", image_title="Sanitaryware"), card_buttons=[Button(button_text="Know More", button_url_redirect="https://www.jaquar.com/en/sanitaryware", button_value="after_redirect")])
thermostatic_mixers_card = Card(card_heading="Thermostatic Mixers", card_body="Thermostatic shower valves, you can control the temperature of the water using modern technology.", card_type="image", card_image=Image(image_url="https://www.jaquar.com/images/thumbs/0012248_thermostatic-mixers_400.jpeg", image_title="Thermostatic Mixers"), card_buttons=[Button(button_text="Know More", button_url_redirect="https://www.jaquar.com/en/thermostatic-mixers", button_value="after_redirect")])
water_heaters_card = Card(card_heading="Water Heaters", card_body="Jaquar's water heater and geysers are of high-quality, and also assure you of its safety!", card_type="image", card_image=Image(image_url="https://www.jaquar.com/images/thumbs/0012251_water-heaters_400.jpeg", image_title="Water Heaters"), card_buttons=[Button(button_text="Know More", button_url_redirect="https://www.jaquar.com/en/water-heaters", button_value="after_redirect")])
whirlpools_card = Card(card_heading="Whirlpools", card_body="Jaquar whirlpool baths are an excellent way to boost circulation naturally throughout the body.", card_type="image", card_image=Image(image_url="https://5.imimg.com/data5/VQ/KX/II/SELLER-16591170/41-500x500.jpg", image_title="Whirlpools"), card_buttons=[Button(button_text="Know More", button_url_redirect="https://www.jaquar.com/en/whirlpools", button_value="after_redirect")])
bathtubs_card = Card(card_heading="Bath Tubs", card_body="The bathtub design is conventionally narrow and elongated, designed to fit an adult laying back and relaxing.", card_type="image", card_image=Image(image_url="https://www.jaquar.com/images/thumbs/0032791_free-standing-bathtubs_400.jpeg", image_title="Bath Tubs"), card_buttons=[Button(button_text="Know More", button_url_redirect="https://www.jaquar.com/en/bath-tub", button_value="after_redirect")])
spas_card = Card(card_heading="Spas", card_body="Jaquar's spa tubs are a technological wonder created to let you relax and restore the balance of body and mind.", card_type="image", card_image=Image(image_url="https://www.jaquar.com/images/thumbs/0012253_spas_400.jpeg", image_title="Spas"), card_buttons=[Button(button_text="Know More", button_url_redirect="https://www.jaquar.com/en/spas", button_value="after_redirect")])
saunas_card = Card(card_heading="Saunas", card_body="Home sauna's wooden interiors and temperature controls allow you to find that sweet spot.", card_type="image", card_image=Image(image_url="https://www.jaquar.com/images/thumbs/0012254_saunas_400.jpeg", image_title="Saunas"), card_buttons=[Button(button_text="Know More", button_url_redirect="https://www.jaquar.com/en/saunas", button_value="after_redirect")])
shower_enclosure_card = Card(card_heading="Shower Enclosure", card_body="Shower Enclosure has become an integral part of the Modern Bathroom", card_type="image", card_image=Image(image_url="https://www.jaquar.com/images/thumbs/0032836_shower-enclosure_400.jpeg", image_title="Shower Enclosure"), card_buttons=[Button(button_text="Know More", button_url_redirect="https://www.jaquar.com/en/shower-enclosures", button_value="after_redirect")])
accessories_card = Card(card_heading="Accessories", card_body="Jaquar's bathroom accessories are affordable and give you value for money!", card_type="image", card_image=Image(image_url="https://www.jaquar.com/images/thumbs/0012258_accessories_400.jpeg", image_title="Accessories"), card_buttons=[Button(button_text="Know More", button_url_redirect="https://www.jaquar.com/en/accessories-4", button_value="after_redirect")])
steam_solutions_card = Card(card_heading="Steam Solutions", card_body="Jaquar steamer for the bathroom is a great way to enjoy the benefits of humidifying water vapour from a high-quality steam", card_type="image", card_image=Image(image_url="https://www.jaquar.com/images/thumbs/0012255_steam-solutions_400.jpeg", image_title="Steam Solutions"), card_buttons=[Button(button_text="Know More", button_url_redirect="https://www.jaquar.com/en/steam-bath-solutions", button_value="after_redirect")])
shower_panels_card = Card(card_heading="Shower Panels", card_body="Shower panels are a single unified system that consists of various functions to experience a luxurious shower experience.", card_type="image", card_image=Image(image_url="https://www.jaquar.com/images/thumbs/0012256_shower-panels_400.jpeg", image_title="Shower Panels"), card_buttons=[Button(button_text="Know More", button_url_redirect="https://www.jaquar.com/en/jaquar-shower-panels", button_value="after_redirect")])
flushing_systems_card = Card(card_heading="Flushing Systems", card_body="Modern flush tank designs offer a sleek look to bathroom spaces along with efficient features like water-saving, easy access etc.", card_type="image", card_image=Image(image_url="https://www.jaquar.com/images/thumbs/0012250_flushing-systems_400.jpeg", image_title="Flushing Systems"), card_buttons=[Button(button_text="Know More", button_url_redirect="https://www.jaquar.com/en/toilet-flushing-systems", button_value="after_redirect")])
plan_your_bathroom_card = Card(card_heading="Plan Your Bathroom", card_body="A Complete Bathroom Solutions where you can conceptualize your own bathroom concept", card_type="image", card_image=Image(image_url="https://www.jaquar.com/images/thumbs/0032805_plan-your-bathroom_400.jpeg", image_title="Plan Your Bathroom"), card_buttons=[Button(button_text="Know More", button_url_redirect="https://www.jaquar.com/en/complete-bathroom-solution", button_value="after_redirect")])
previous_menu_card = Card(card_heading="Previous Menu", card_body="Click here to go to previous menu", card_type="image", card_image=Image(image_url="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSLWHVis-nhRk-uhpI9D3TkAiUfORghap79O4tK6MtQd6mT-oTYVvp-X9tQxLxVSDRCkOw&amp;usqp=CAU", image_title="Previous Menu"), card_buttons=[Button(button_text="Know More", button_url_redirect="https://www.jaquar.com/en/previous-menu", button_value="after_redirect")])
bathroom_products_carousel = Carousel(carousel_type="card", carousel_items=[new_arrival_card,faucets_card,showers_card,sanitaryware_card,thermostatic_mixers_card,water_heaters_card,whirlpools_card,bathtubs_card,spas_card,saunas_card,shower_enclosure_card,accessories_card,steam_solutions_card,shower_panels_card,flushing_systems_card,plan_your_bathroom_card,previous_menu_card])
bathroom_products_response = Response(response_items = [ResponseElement(type="label", element=bathroom_products_label ), ResponseElement(type="carousel", element=bathroom_products_carousel)])
bathroom_products_intent = Intent(tag="bathroom_products", response=bathroom_products_response, pattern=["Bathroom Products", "bathroom_products", "Bathroom", "show me bathroom products","New Bathroom Products", "New Bathroom arrivals" ,"Faucets","Showers","Sanitaryware","Thermostatic Mixers","Water Heaters","Whirlpools", "Bath Tubs", "Spas", "Saunas", "Shower Enclosure","Bathroom Accessories", "Steam Solutions","Shower Panels","Flushing Systems","Plan Your Bathroom"])

lighting_products_label = Label(label_body="We have categorized our lighting products in two different sections please choose from below.", label_type="default", label_value="lighting_products")
lighting_products_list = ListGroup(listgroup_title="Choose option", list_items=[Button(button_text="Professional Lighting", button_value="professional_lighting"),Button(button_text="Consumer Lighting", button_value="Consumer_lighting"),Button(button_text="Go back to Previous Menu", button_value="previous_menu"), Button(button_text="Main Menu", button_value="Main Menu")], list_value="choose_options")
lighting_products_response = Response(response_items = [ResponseElement(type="label", element=lighting_products_label ), ResponseElement(type="list", element=lighting_products_list) ])
lighting_products_intent = Intent(tag="lighting_products", response=lighting_products_response, pattern=["Lighting Products", "lighting_products", "Lighting", "show me lighting products","light","lights","bulb"])


professional_lighting_label = Label(label_body="Jaquar offers various professional lighting products. Please select from the menu given below", label_type="default", label_value="professional_lighting_products")
linear_flex_card = Card(card_heading="Linear Flex | Jaquar", card_body="Jaquar Linear Flex is a state of the art luminaires solution that provides maximum flexibility.", card_type="image", card_image=Image(image_url="https://www.jaquar.com/images/thumbs/0040948_linear-flex_400.jpeg", image_title="Linear Flex | Jaquar"), card_buttons=[Button(button_text="Know More", button_url_redirect="https://www.jaquar.com/en/linear-flex", button_value="after_redirect")])
flood_lights_card = Card(card_heading="Flood Lights | Jaquar", card_body="Jaquar Flood Lights are perfect for creating varied effects such as flood lighting effect, grazing, decorative lighting and more. ", card_type="image", card_image=Image(image_url="https://www.jaquar.com/images/thumbs/0040945_flood-lights_400.jpeg", image_title="Flood Lights | Jaquar"), card_buttons=[Button(button_text="Know More", button_url_redirect="https://www.jaquar.com/en/flood-lights", button_value="after_redirect")])
dot_lights_card = Card(card_heading="Dot Lights | Jaquar", card_body="ntroducing the most unique and advanced direct-view luminaries which are highly flexible and can fulfill various applications.", card_type="image", card_image=Image(image_url="https://www.jaquar.com/images/thumbs/0040937_dot-lights_400.jpeg", image_title="Dot Lights | Jaquar"), card_buttons=[Button(button_text="Know More", button_url_redirect="https://www.jaquar.com/en/dot-lights", button_value="after_redirect")])
flexi_wallwasher_card = Card(card_heading="Flexi Wallwasher | Jaquar", card_body="Jaquar conceived the idea of flexible wallwasher solutions to provide maximum flexibility and assist designers and Architects to overcome challenges posed by standard luminaires in various projects", card_type="image", card_image=Image(image_url="https://www.jaquar.com/images/thumbs/0040938_flexi-wallwasher_400.jpeg", image_title="Flexi Wallwasher | Jaquar"), card_buttons=[Button(button_text="Know More", button_url_redirect="https://www.jaquar.com/en/flexi-wallwasher", button_value="after_redirect")])
ground_burials_card = Card(card_heading="Ground Burials | Jaquar", card_body="Jaquar ground burials are designed to enhance architectures, they can be used in varied applications like column uplighter, tree uplighter, etc.", card_type="image", card_image=Image(image_url="https://www.jaquar.com/images/thumbs/0040939_ground-burials_400.jpeg", image_title="Ground Burials | Jaquar"), card_buttons=[Button(button_text="Know More", button_url_redirect="https://www.jaquar.com/en/ground-burials", button_value="after_redirect")])
guardrail_lights_card = Card(card_heading="Guardrail Lights | Jaquar", card_body="Jaquar guardrail lights and handrail lights are a unique product solution designed to be a integrated part of the rails.", card_type="image", card_image=Image(image_url="https://www.jaquar.com/images/thumbs/0040940_guardrail-lights_400.jpeg", image_title="Guardrail Lights | Jaquar"), card_buttons=[Button(button_text="Know More", button_url_redirect="https://www.jaquar.com/en/guardrail-lights", button_value="after_redirect")])
spot_projector_card = Card(card_heading="Spot Projectors | Jaquar", card_body="Jaquar spot projectors provide best in class optics from ultra narrow beam to wide beam.", card_type="image", card_image=Image(image_url="https://www.jaquar.com/images/thumbs/0040941_spot-projectors_400.jpeg", image_title="Spot Projectors | Jaquar"), card_buttons=[Button(button_text="Know More", button_url_redirect="https://www.jaquar.com/en/spot-projector", button_value="after_redirect")])
trunking_lights_card = Card(card_heading="Trunking Lights | Jaquar", card_body="Jaquar trunking lights have seamless body and invisible connector design for beautiful aesthetics and are designed to create a even and soothing lighting effect.", card_type="image", card_image=Image(image_url="https://www.jaquar.com/images/thumbs/0040942_trunking-lights_400.jpeg", image_title="Trunking Lights | Jaquar"), card_buttons=[Button(button_text="Know More", button_url_redirect="https://www.jaquar.com/en/trunking-lights", button_value="after_redirect")])
under_water_lights_card = Card(card_heading="Under Water Lights | Jaquar", card_body="Jaquar underwater lights are designed with high a quality 304/316 Stainless Steel housing which allows for longer life in both fresh water as well as salt water.", card_type="image", card_image=Image(image_url="https://www.jaquar.com/images/thumbs/0040943_under-water-lights_400.jpeg", image_title="Under Water Lights | Jaquar"), card_buttons=[Button(button_text="Know More", button_url_redirect="https://www.jaquar.com/en/under-water-lights", button_value="after_redirect")])
wall_washer_card = Card(card_heading="Wall Washer | Jaquar", card_body="Introducing a wide range of high performance Linear Wall washers designed to highlight key architectural features of buildings or projects.", card_type="image", card_image=Image(image_url="https://www.jaquar.com/images/thumbs/0040944_wall-washer_400.jpeg", image_title="Wall Washer | Jaquar"), card_buttons=[Button(button_text="Know More", button_url_redirect="https://www.jaquar.com/en/wall-washer", button_value="after_redirect")])
window_lights_card = Card(card_heading="Window Lights | Jaquar", card_body="Jaquar introduces a specialized selection of window lights to meet various applications.", card_type="image", card_image=Image(image_url="https://www.jaquar.com/images/thumbs/0040949_window-lights_400.jpeg", image_title="Window Lights | Jaquar"), card_buttons=[Button(button_text="Know More", button_url_redirect="https://www.jaquar.com/en/window-lights", button_value="after_redirect")])
linear_inground_lights_card = Card(card_heading="Linear Inground Lights | Jaquar", card_body="Building on the legacy of wall washers, Jaquar has launched the linear inground series of luminaires.", card_type="image", card_image=Image(image_url="https://www.jaquar.com/images/thumbs/0040950_linear-inground-lights_400.jpeg", image_title="Linear Inground Lights | Jaquar"), card_buttons=[Button(button_text="Know More", button_url_redirect="https://www.jaquar.com/en/linear-inground", button_value="after_redirect")])
linear_light_card = Card(card_heading="Linear Lights | Jaquar", card_body="Linear Lights are a especially designed direct view luminaires which come with anti glare technology.", card_type="image", card_image=Image(image_url="https://www.jaquar.com/images/thumbs/0040951_linear-light_400.jpeg", image_title="Linear Lights | Jaquar"), card_buttons=[Button(button_text="Know More", button_url_redirect="https://www.jaquar.com/en/linear-light", button_value="after_redirect")])
professional_lighting_carousel = Carousel(carousel_type="card", carousel_items=[guardrail_lights_card, ground_burials_card, trunking_lights_card, spot_projector_card, under_water_lights_card, wall_washer_card, window_lights_card, linear_inground_lights_card, linear_light_card])
professional_lighting_response = Response(response_items = [ResponseElement(type="label", element=professional_lighting_label ), ResponseElement(type="carousel", element=professional_lighting_carousel)])
professional_lighting_intent = Intent(tag="professional_lighting", response=professional_lighting_response, pattern=["professional_lighting","professional lighting","Linear Flex","Flood Lights","Dot Lights","Flexi Wallwasher","Ground Burials","Guardrail Lights","Spot Projectors","Trunking Lights","Under Water","Wall Washer","Window Lights","Linear Inground","Linear Lights"])


consumer_lighting_label = Label(label_body="Jaquar offers various consumer lighting products. Please select from the menu given below", label_type="default", label_value="consumer_lighting_products")
led_downlights_card = Card(card_heading="LED Downlights | Jaquar", card_body="LED Downlights for consumer by Jaquar.", card_type="image", card_image=Image(image_url="https://www.jaquar.com/images/thumbs/0041827_led-downlights_400.jpeg", image_title="LED Downlights | Jaquar"), card_buttons=[Button(button_text="Know More", button_url_redirect="https://www.jaquar.com/en/led-downlights", button_value="after_redirect")])
led_battens_card = Card(card_heading="LED Battens | Jaquar", card_body="LED Battens for consumer by Jaquar.", card_type="image", card_image=Image(image_url="https://www.jaquar.com/images/thumbs/0041828_led-battens_400.jpeg", image_title="LED Battens | Jaquar"), card_buttons=[Button(button_text="Know More", button_url_redirect="https://www.jaquar.com/en/led-battens-2", button_value="after_redirect")])
led_panels_card = Card(card_heading="LED Panels | Jaquar", card_body="LED Panels for consumer by Jaquar.", card_type="image", card_image=Image(image_url="https://www.jaquar.com/images/thumbs/0041829_led-panels_400.jpeg", image_title="LED Panels | Jaquar"), card_buttons=[Button(button_text="Know More", button_url_redirect="https://www.jaquar.com/en/led-panels-2", button_value="after_redirect")])
led_bulbs_card = Card(card_heading="LED Bulbs | Jaquar", card_body="LED Bulbs for consumer by Jaquar.", card_type="image", card_image=Image(image_url="https://www.jaquar.com/images/thumbs/0041830_led-bulbs_400.jpeg", image_title="LED Bulbs | Jaquar"), card_buttons=[Button(button_text="Know More", button_url_redirect="https://www.jaquar.com/en/led-bulbs", button_value="after_redirect")])
led_spot_lights_card = Card(card_heading="LED Spot Lights | Jaquar", card_body="LED Spot Lights for consumer by Jaquar.", card_type="image", card_image=Image(image_url="https://www.jaquar.com/images/thumbs/0041832_led-spot-lights_400.jpeg", image_title="LED Spot Lights | Jaquar"), card_buttons=[Button(button_text="Know More", button_url_redirect="https://www.jaquar.com/en/led-spot-lights", button_value="after_redirect")])
led_strip_lights_card = Card(card_heading="LED Strip Lights | Jaquar", card_body="LED Strip Lights for consumer by Jaquar.", card_type="image", card_image=Image(image_url="https://www.jaquar.com/images/thumbs/0041833_led-strip-lights_400.jpeg", image_title="LED Strip Lights | Jaquar"), card_buttons=[Button(button_text="Know More", button_url_redirect="https://www.jaquar.com/en/led-strip-lights", button_value="after_redirect")])
led_street_lights_card = Card(card_heading="LED Street Lights | Jaquar", card_body="LED Street Lights for consumer by Jaquar.", card_type="image", card_image=Image(image_url="https://www.jaquar.com/images/thumbs/0041834_led-street-lights_400.jpeg", image_title="LED Street Lights | Jaquar"), card_buttons=[Button(button_text="Know More", button_url_redirect="https://www.jaquar.com/en/led-street-lights", button_value="after_redirect")])
consumer_lighting_carousel = Carousel(carousel_type="card", carousel_items=[led_downlights_card, led_battens_card, led_panels_card, led_bulbs_card, led_spot_lights_card, led_strip_lights_card, led_street_lights_card])
consumer_lighting_response = Response(response_items = [ResponseElement(type="label", element=consumer_lighting_label ), ResponseElement(type="carousel", element=consumer_lighting_carousel)])
consumer_lighting_intent = Intent(tag="consumer_lighting", response=consumer_lighting_response, pattern=["consumer_lighting","consumer lighting","LED Downlights","LED Battens","LED Panels","LED Bulbs","LED Spot Lights","LED Strip Lights","LED Street Lights"])


call_purchase_assistant_label = Label(label_body="If you need any help we are one call away from you please feel free to call us at anytime.", label_type="default", label_value="call_purchase_assistant")
call_purchase_assistant_url = Url(url_title="1800-120-332222", url_url="tel://1800-120-332222")
call_purchase_assistant_list = ListGroup(listgroup_title="Choose option", list_items=[Button(button_text="Other queries", button_value="Other queries"), Button(button_text="Go back to Previous Menu", button_value="previous_menu"), Button(button_text="Main Menu", button_value="Main Menu"), Button(button_text="Exit", button_value="exit"), ], list_value="choose_options")
call_purchase_assistant_response = Response(response_items = [ResponseElement(type="label", element=call_purchase_assistant_label ), ResponseElement(type="url", element=call_purchase_assistant_url ), ResponseElement(type="list", element=call_purchase_assistant_list) ])
call_purchase_assistant_intent = Intent(tag="call_purchase_assistant", response=call_purchase_assistant_response, pattern=["Call Purchase Assistant", "call_purchase_assistant"])

other_queries_url = Url(url_title="Contact Us", url_url="https://www.jaquar.com/en/contactus?redirect=contact")
other_queries_list = ListGroup(listgroup_title="Choose option", list_items=[Button(button_text="Feedback/ Suggestions", button_value="Feedback") ,Button(button_text="FAQ", button_value="FAQ"), Button(button_text="Go back to Previous Menu", button_value="previous_menu"), Button(button_text="Main Menu", button_value="Main Menu")], list_value="choose_options")
other_queries_response = Response(response_items = [ResponseElement(type="url", element=other_queries_url ), ResponseElement(type="list", element=other_queries_list) ])
other_queries_intent = Intent(tag="other_queries", response=other_queries_response, pattern=["Other queries", "other_queries"])

faq_label = Label(label_body="Please choose from the options below", label_type="default", label_value="faq")
faq_list = ListGroup(listgroup_title="Choose option", list_items=[Button(button_text="Can we buy the products from Jaquar orientation centre?", button_value="Can we buy the products from Jaquar orientation centre?"), Button(button_text="Where do I get Jaquar Orientation Center addresses? Or how can I locate Jaquar orientation centres?", button_value="Where do I get Jaquar Orientation Center addresses? Or how can I locate Jaquar orientation centres?"), Button(button_text="What is PMS and PMC?", button_value="What is PMS and PMC?"), Button(button_text="How to avoid slipping danger from the bathroom?", button_value="How to avoid slipping danger from the bathroom?"), Button(button_text="What do you mean by Jaquar complete bathing solutions?", button_value="What do you mean by Jaquar complete bathing solutions?"), Button(button_text="Can LED lighting harm our eyesight?", button_value="Can LED lighting harm our eyesight?"), Button(button_text="Are LED light bulbs worth the money?", button_value="Are LED light bulbs worth the money?"), Button(button_text="What are the best light bulbs for enclosures?", button_value="What are the best light bulbs for enclosures?"), Button(button_text="Go back to Previous Menu", button_value="previous_menu")], list_value="choose_options")
faq_response = Response(response_items = [ResponseElement(type="label", element=faq_label ), ResponseElement(type="list", element=faq_list) ])
faq_intent = Intent(tag="faq", response=faq_response, pattern=["FAQ", "Frequently asked questions", "i want to know more"])

exit_label1 = Label(label_body="Thank you for giving your time.")
exit_label2= Label(label_body="Have a nice day, Bye.")
exit_response = Response(response_items = [ResponseElement(type="label", element=exit_label1 ), ResponseElement(type="label", element=exit_label2) ])
exit_intent = Intent(tag="exit", response=exit_response, pattern=["exit","ok goodbye","byee","chat later","i said goodbye!","okay bye","toodles","cya","close this talk","sleep!","good bye.","bye","see you soon","bye bye","cee you later","farewell","bye bye take care","then bye","ok, bye","go awy","end the conversation","bye for now","sayonara","bye!","bye bot","later you","ok bye","good by","bye bye bot","ciao","you can go now","byr","well....goodbye.","ciao.","bye was nice talking to you","ok.bye","bye bye see you soon","good bye for now","goodbye","good bye","thank you, bye","leave me alone","catch you later","see you around","see you later","hang up","see u later","gotta go","goodbye.","bye-bye","fine for now","bye!!","tlak to you later","cheerio","that's all for now","take care","ta ta for now","time to go","bye bye see you","thanks bye","end chat","bye .","bye then","goodbye for now","adios","bye bye ","ok goodbye then","see you","i gotta go","leave","thanks bye bye","alright bye","see ya","goodbye see you later","goodbye!","see you . bye"])

after_redirect_label = Label(label_body="Please choose from the options below", label_type="default", label_value="after_redirect")
after_redirect_list = ListGroup(listgroup_title="Choose option", list_items=[Button(button_text="Go back to Previous Menu", button_value="previous_menu"), Button(button_text="Main Menu", button_value="Main Menu"), Button(button_text="Exit", button_value="exit"), ], list_value="choose_options")
after_redirect_response = Response(response_items = [ResponseElement(type="label", element=after_redirect_label ), ResponseElement(type="list", element=after_redirect_list) ])
after_redirect_intent = Intent(tag="after_redirect", response=after_redirect_response, pattern=["after_redirect"])

center_virtual_tour_list = ListGroup(list_title="Choose Options", list_items=[Button(button_text="Call Purchase Assistant", button_value="Call Purchase Assistant"), Button(button_text="Locate the nearest dealer", button_value="Locate the nearest dealer"), Button(button_text="Go back to Main Menu", button_value="Main Menu"), Button(button_text="Exit", button_value="Exit")], list_value="View Orientation Center Virtual Tour")
center_virtual_tour_response = Response(response_items = [ResponseElement(type="list", element=center_virtual_tour_list)])
center_virtual_tour_intent = Intent(tag="center_virtual_tour", response=center_virtual_tour_response, pattern=["View Orientation Center Virtual Tour", "Orientation Center Virtual Tour", "center_virtual_tour"])

dealer_location_label = Label(label_body="Find out our nearest dealer locator for Jaquar and Jaquar lighting solutions.")
dealer_location_url = Url(url_title="Locate Dealers", url_url="https://www.jaquar.com/en/find-dealers")
dealer_location_response = Response(response_items = [ResponseElement(type="label", element=dealer_location_label ), ResponseElement(type="url", element=dealer_location_url)])
dealer_location_intent = Intent(tag="dealer_location", response=dealer_location_response, pattern=["dealer_location","Locate the nearest dealer", "Dealer Location", "Jaguar Dealer", "Jaguar Lighting Dealer"])

download_customer_catalogue_label = Label(label_body="You can download our product catalogue to find out more about our exquisite designs!")
download_customer_catalogue_url1 = Url(url_title="Bathroom catalogue", url_url="https://www.jaquar.com/pdf/customer-guide-vol18.2.pdf")
download_customer_catalogue_url2 = Url(url_title="Lighting catalogue", url_url="https://www.jaquarlighting.com/catalogue")
download_customer_catalogue_list = ListGroup(list_title="Choose Options", list_items=[Button(button_text="Go back to Previous Menu", button_value="previous_menu")], list_value="Download Customer catalogue")
download_customer_catalogue_response = Response(response_items = [ResponseElement(type="label", element=download_customer_catalogue_label ), ResponseElement(type="url", element=download_customer_catalogue_url1), ResponseElement(type="url", element=download_customer_catalogue_url2), ResponseElement(type="list", element=download_customer_catalogue_list)])
download_customer_catalogue_intent = Intent(tag="download_customer_catalogue", response=download_customer_catalogue_response, pattern=["Download Customer catalogue", "download_customer_catalogue"])

customer_service_label = Label(label_body="Thank you for contacting Jaquar customer care.")
customer_service_label2 = Label(label_body="We are available Monday-Saturday 9:00 AM to 6:00 PM")
customer_service_label3 = Label(label_body="Customer Support For lighting")
customer_service_url = Url(url_title="1800-212-6808", url_url="tel://1800-212-6808")
customer_service_label4 = Label(label_body="Customer support for Bathroom")
customer_service_url2 = Url(url_title="1800-121-6808", url_url="tel://1800-121-6808")
customer_service_list = ListGroup(list_title="Choose Options", list_items=[Button(button_text="Go back to Main Menu", button_value="Main Menu"), Button(button_text="Exit", button_value="Exit")], list_value="Customer Service")
customer_service_response = Response(response_items = [ResponseElement(type="label", element=customer_service_label ), ResponseElement(type="label", element=customer_service_label2 ), ResponseElement(type="label", element=customer_service_label3 ), ResponseElement(type="url", element=customer_service_url ), ResponseElement(type="label", element=customer_service_label4 ), ResponseElement(type="url", element=customer_service_url2 ), ResponseElement(type="list", element=customer_service_list)])
customer_service_intent = Intent(tag="customer_service", response=customer_service_response, pattern=["Customer Service", "customer_service", "customer service contact","customer support"])

download_app_label = Label(label_body="You can download our product catalogue to find out more about our exquisite designs!")
download_app_list = ListGroup(list_title="Choose Options", list_items=[Button(button_text="App Store", button_value="after_redirect", button_url_redirect="https://apps.apple.com/in/app/jaquar/id1326726197"), Button(button_text="Google Play", button_value="after_redirect", button_url_redirect="https://play.google.com/store/apps/details?id=com.agbe.jaquar&hl=en_IN"), Button(button_text="Go back to Previous Menu", button_value="previous_menu")], list_value="Download Our Mobile Apps")
download_app_response = Response(response_items = [ResponseElement(type="label", element=download_app_label ), ResponseElement(type="list", element=download_app_list)])
download_app_intent = Intent(tag="download_app", response=download_app_response, pattern=["Download Our Mobile App", "download_app"])


app_store_url = Url(url_title="App Store Url", url_url="https://apps.apple.com/in/app/jaquar/id1326726197")
app_store_list = ListGroup(list_title="Choose Options", list_items=[Button(button_text="Go back to Main Menu", button_value="Main Menu"), Button(button_text="Go back to Previous Menu", button_value="previous_menu"), Button(button_text="Exit", button_value="Exit")], list_value="App Store")
app_store_response = Response(response_items = [ResponseElement(type="url", element=app_store_url ), ResponseElement(type="list", element=app_store_list)])
app_store_intent = Intent(tag="app_store", response=app_store_response, pattern=["App Store", "apple app", "apple store", "ios app"])


google_play_url = Url(url_title="Google Play Url", url_url="https://play.google.com/store/apps/details?id=com.agbe.jaquar&hl=en_IN")
google_play_list = ListGroup(list_title="Choose Options", list_items=[Button(button_text="Go back to Main Menu", button_value="Main Menu"), Button(button_text="Go back to Previous Menu", button_value="previous_menu"), Button(button_text="Exit", button_value="Exit")], list_value="Google Play")
google_play_response = Response(response_items = [ResponseElement(type="url", element=google_play_url ), ResponseElement(type="list", element=google_play_list)])
google_play_intent = Intent(tag="google_play", response=google_play_response, pattern=["Google Play", "android app", "google app", "google_play"])

social_media_list = ListGroup(list_title="Choose Options", list_items=[Button(button_text="LinkedIn", button_value="LinkedIn"), Button(button_text="Twitter", button_value="Twitter"), Button(button_text="Facebook", button_value="Facebook"), Button(button_text="YouTube", button_value="YouTube"), Button(button_text="Instagram", button_value="Instagram"), Button(button_text="Go back to Previous Menu", button_value="previous_menu")], list_value="Social Media")
social_media_response = Response(response_items = [ResponseElement(type="list", element=social_media_list)])
social_media_intent = Intent(tag="social_media", response=social_media_response, pattern=["Social Media", "social_media", "Visit Our Social Media Handles"])

professional_list = ListGroup(list_title="Choose Options", list_items=[Button(button_text="Architect / Interior designer", button_value="professional_service_form"), Button(button_text="Builder/Consultant", button_value="professional_service_form"), Button(button_text="Retailer", button_value="professional_service_form"), Button(button_text="Contractor", button_value="professional_service_form"), Button(button_text="Lighting consultant", button_value="professional_service_form"), Button(button_text="Plumber", button_value="labour_service_form"), Button(button_text="Electricians", button_value="labour_service_form"), Button(button_text="Generate BOQ", button_value="professional_service_form"), Button(button_text="Newsletter Updates", button_value="professional_service_form"), Button(button_text="Go back to Previous Menu", button_value="previous_menu")], list_value="Professional")
professional_response = Response(response_items = [ResponseElement(type="list", element=professional_list)])
professional_intent = Intent(tag="professional", response=professional_response, pattern=["professional", "I am a professional", "architect","interior designer", "builder", "consultant", "retailer", "contractor", "lighting consultant", "plumber", "electricians", "generate BOQ", "newsletter updates"])

professional_service_form_label = Label(label_body="Please fill up the following details.", label_type="default", label_value="professional_service_form")
professional_service_form_name = TextInput(textinput_placeholder="Please enter your name", textinput_type="default", textinput_value="professional_name")
professional_service_form_email = TextInput(textinput_placeholder="Please enter your Email", textinput_type="email", textinput_value="professional_email")
professional_service_form_phone = TextInput(textinput_placeholder="Please enter your Phone Number", textinput_type="phone", textinput_value="professional_phone")
professional_service_form_form = Form(form_title="Contact Details", form_items=[professional_service_form_name, professional_service_form_email, professional_service_form_phone], form_value="contact_details", form_submit_button=Button(button_text="Submit", button_value="professional_service", button_type="submit"))
professional_service_form_response = Response(response_items = [ResponseElement(type="label", element=professional_service_form_label ), ResponseElement(type="form", element=professional_service_form_form)], context=["professional_name","professional_email","professional_phone"])
professional_service_form_intent = Intent(tag="professional_service_form", response=professional_service_form_response, pattern=["professional_service_form","professional service form"])

labour_service_form_label = Label(label_body="Please fill up the following details.", label_type="default", label_value="labour_service_form")
labour_service_form_name = TextInput(textinput_placeholder="Please enter your name", textinput_type="default", textinput_value="labour_name")
labour_service_form_email = TextInput(textinput_placeholder="Please enter your Email", textinput_type="email", textinput_value="labour_email")
labour_service_form_form = Form(form_title="Contact Details", form_items=[labour_service_form_name, labour_service_form_email], form_value="contact_details", form_submit_button=Button(button_text="Submit", button_value="labour_service", button_type="submit"))
labour_service_form_response = Response(response_items = [ResponseElement(type="label", element=labour_service_form_label ), ResponseElement(type="form", element=labour_service_form_form)], context=["labour_name","labour_email"])
labour_service_form_intent = Intent(tag="labour_service_form", response=labour_service_form_response, pattern=["labour_service_form", "labour service form"])

professional_service_list = ListGroup(list_title="Choose Options", list_items=[Button(button_text="Download professional catalogue", button_value="download_professional_catalogue"), Button(button_text="CAD drawings", button_value="CAD drawings"), Button(button_text="Product 3D view", button_value="Product 3D view"), Button(button_text="Locate dealers", button_value="Dealer Location"), Button(button_text="Call purchase assistant", button_value="Call purchase assistant"), Button(button_text="Orientation centre virtual tour", button_value="Orientation centre virtual tour"), Button(button_text="New Arrivals", button_value="New Arrivals"), Button(button_text="Bathroom Products", button_value="Bathroom Products"), Button(button_text="Lighting Products", button_value="Lighting Products"), Button(button_text="Go back to Previous Menu", button_value="previous_menu"), Button(button_text="Go back to Main Menu", button_value="Main Menu")], list_value="professional_service")
professional_service_response = Response(response_items = [ResponseElement(type="list", element=professional_service_list)])
professional_service_intent = Intent(tag="professional_service", response=professional_service_response, pattern=["professional_service", "professional service"])

download_professional_catalogue_label = Label(label_body="Is there anything else I can assist you with?", label_type="default", label_value="download_professional_catalogue")
download_professional_catalogue_url = Url(url_title="View professional catalogue here", url_url="https://view.publitas.com/jaquar/technical-catalogue-for-jaquar/")
download_professional_catalogue_list = ListGroup(list_title="Choose Options", list_items=[Button(button_text="Call Purchase Assistant", button_value="Call Purchase Assistant"), Button(button_text="Locate the nearest dealer", button_value="dealer location"), Button(button_text="Go back to Main Menu", button_value="Main Menu"), Button(button_text="Go back to Previous Menu", button_value="previous_menu"), Button(button_text="Exit", button_value="Exit")], list_value="Output step 1")
download_professional_catalogue_response = Response(response_items = [ResponseElement(type="label", element=download_professional_catalogue_label ), ResponseElement(type="url", element=download_professional_catalogue_url), ResponseElement(type="list", element=download_professional_catalogue_list)])
download_professional_catalogue_intent = Intent(tag="download_professional_catalogue", response=download_professional_catalogue_response, pattern=["download_professional_catalogue", "download professional catalogue"])

cad_drawings_label = Label(label_body="Is there anything else I can assist you with?", label_type="default", label_value="cad_drawings")
cad_drawings_url = Url(url_title="View CAD drawings here", url_url="https://cloud.jaquar.com/jcloud/index.php/s/4EXEgiBzgH89SxA")
cad_drawings_list = ListGroup(list_title="Choose Options", list_items=[Button(button_text="Call Purchase Assistant", button_value="Call Purchase Assistant"), Button(button_text="Locate the nearest dealer", button_value="dealer location"), Button(button_text="Go back to Main Menu", button_value="Main Menu"), Button(button_text="Go back to Previous Menu", button_value="previous_menu"), Button(button_text="Exit", button_value="Exit")], list_value="Output step 1")
cad_drawings_response = Response(response_items = [ResponseElement(type="label", element=cad_drawings_label ), ResponseElement(type="url", element=cad_drawings_url), ResponseElement(type="list", element=cad_drawings_list)])
cad_drawings_intent = Intent(tag="cad_drawings", response=cad_drawings_response, pattern=["cad_drawings", "cad", "cad drawings"])

product_3d_view_label = Label(label_body="Is there anything else I can assist you with?", label_type="default", label_value="product_3d_view")
product_3d_view_url = Url(url_title="Watch Product 3D view here", url_url="https://3dwarehouse.sketchup.com/by/jaquar")
product_3d_view_list = ListGroup(list_title="Choose Options", list_items=[Button(button_text="Call Purchase Assistant", button_value="Call Purchase Assistant"), Button(button_text="Locate the nearest dealer", button_value="Dealer Location"), Button(button_text="Go back to Main Menu", button_value="Main Menu"), Button(button_text="Go back to Previous Menu", button_value="previous_menu"), Button(button_text="Exit", button_value="Exit")], list_value="Output step 1")
product_3d_view_response = Response(response_items = [ResponseElement(type="label", element=product_3d_view_label ), ResponseElement(type="url", element=product_3d_view_url), ResponseElement(type="list", element=product_3d_view_list)])
product_3d_view_intent = Intent(tag="product_3d_view", response=product_3d_view_response, pattern=["product_3d_view", "product 3d view"])

new_arrivals_label = Label(label_body="Is there anything else I can assist you with?", label_type="default", label_value="new_arrivals")
new_arrivals_url = Url(url_title="Watch New Arrivals here", url_url="https://www.jaquar.com/en/new-arrival?redirect=arrival")
new_arrivals_list = ListGroup(list_title="Choose Options", list_items=[Button(button_text="Call Purchase Assistant", button_value="Call Purchase Assistant"), Button(button_text="Locate the nearest dealer", button_value="Dealer Location"), Button(button_text="Go back to Main Menu", button_value="Main Menu"), Button(button_text="Go back to Previous Menu", button_value="previous_menu"), Button(button_text="Exit", button_value="Exit")], list_value="Output step 1")
new_arrivals_response = Response(response_items = [ResponseElement(type="label", element=new_arrivals_label ), ResponseElement(type="url", element=new_arrivals_url), ResponseElement(type="list", element=new_arrivals_list)])
new_arrivals_intent = Intent(tag="new_arrivals", response=new_arrivals_response, pattern=["new_arrivals", "New Arrivals"])

labour_service_list = ListGroup(list_title="Choose Options", list_items=[Button(button_text="Professional catalogue", button_value="Download professional catalogue"), Button(button_text="Installation video", button_value="CAD drawings"), Button(button_text="Catalogue download", button_value="Orientation centre virtual tour"), Button(button_text="New Arrivals", button_value="New Arrivals"), Button(button_text="Go back to Previous Menu", button_value="previous_menu"), Button(button_text="Go back to Main Menu", button_value="Main Menu"), Button(button_text="Exit", button_value="Exit")], list_value="labour service")
labour_service_response = Response(response_items = [ResponseElement(type="list", element=labour_service_list)])
labour_service_intent = Intent(tag="labour_service", response=labour_service_response, pattern=["labour_service", "labour service"])

installation_video_label = Label(label_body="Is there anything else I can assist you with?", label_type="default", label_value="installation_video")
installation_video_url = Video(video_title="Watch Installation video here", video_url="https://www.youtube.com/playlist?list=PLh8cYkXxhmec_wQDaNSvo485ZlxGcYIPR")
installation_video_list = ListGroup(list_title="Choose Options", list_items=[Button(button_text="Call Purchase Assistant", button_value="Call Purchase Assistant"), Button(button_text="Locate the nearest dealer", button_value="Dealer Location"), Button(button_text="Go back to Main Menu", button_value="Main Menu"), Button(button_text="Go back to Previous Menu", button_value="previous_menu"), Button(button_text="Exit", button_value="Exit")], list_value="Output step 1")
installation_video_response = Response(response_items = [ResponseElement(type="label", element=installation_video_label ), ResponseElement(type="url", element=installation_video_url), ResponseElement(type="list", element=installation_video_list)])
installation_video_intent = Intent(tag="installation_video", response=installation_video_response, pattern=["installation_video", "installation video", "youtube video installation"])

catalogue_download_label = Label(label_body="Is there anything else I can assist you with?", label_type="default", label_value="catalogue_download")
catalogue_download_url = Url(url_title="Download  Catalogue here", url_url="https://www.jaquar.com/pdf/customer-guide-vol18.2.pdf")
catalogue_download_list = ListGroup(list_title="Choose Options", list_items=[Button(button_text="Call Purchase Assistant", button_value="Call Purchase Assistant"), Button(button_text="Locate the nearest dealer", button_value="Dealer Location"), Button(button_text="Go back to Main Menu", button_value="Main Menu"), Button(button_text="Go back to Previous Menu", button_value="previous_menu"), Button(button_text="Exit", button_value="Exit")], list_value="Output step 1")
catalogue_download_response = Response(response_items = [ResponseElement(type="label", element=catalogue_download_label ), ResponseElement(type="url", element=catalogue_download_url), ResponseElement(type="list", element=catalogue_download_list)])
catalogue_download_intent = Intent(tag="catalogue_download", response=catalogue_download_response, pattern=["catalogue_download", "catalogue download", "download catalogue"])


## Social Links
linkedin_url = Url(url_title="Check our linkedIn", url_url="https://www.linkedin.com/checkpoint/challengesV2/AQEbVoUWDVezVwAAAYAno8EygFDlBJ5y6NDfxBej4Bl1M0pYMW5u8jZjGMjieQgnDotqEn9oxHS-MDxY2c4-f7nbTsFzE9H4Bg?original_referer=https%3A%2F%2Fchatbot.hellotars.com%2F")
twitter_url = Url(url_title="Check our Twitter", url_url="https://twitter.com/jaquargroup")
facebook_url = Url(url_title="Check our Facebook", url_url="https://www.facebook.com/JaquarIndia")
youtube_url = Url(url_title="Check our YouTube", url_url="https://www.youtube.com/user/jaquarindia")
instagram_url = Url(url_title="Check our Instagram", url_url="https://www.instagram.com/jaquarindia/")
common_list = ListGroup(list_title="Choose Options", list_items=[Button(button_text="Go back to Main Menu", button_value="Main Menu"), Button(button_text="Exit", button_value="Exit")], list_value="social_links")

linkedin_response = Response(response_items = [ResponseElement(type="url", element=linkedin_url), ResponseElement(type="list", element=common_list)])
linkedin_intent = Intent(tag="linkedin", response=linkedin_response, pattern=["LinkedIn", "linkedin account", "linkedin page"])
twitter_response = Response(response_items = [ResponseElement(type="url", element=twitter_url), ResponseElement(type="list", element=common_list)])
twitter_intent = Intent(tag="twitter", response=twitter_response, pattern=["Twitter", "twitter account", "twitter page"])
facebook_response = Response(response_items = [ResponseElement(type="url", element=facebook_url), ResponseElement(type="list", element=common_list)])
facebook_intent = Intent(tag="facebook", response=facebook_response, pattern=["Facebook", "facebook account", "facebook page"])
youtube_response = Response(response_items = [ResponseElement(type="url", element=youtube_url), ResponseElement(type="list", element=common_list)])
youtube_intent = Intent(tag="youtube", response=youtube_response, pattern=["YouTube", "youtube account", "youtube page"])
instagram_response = Response(response_items = [ResponseElement(type="url", element=instagram_url), ResponseElement(type="list", element=common_list)])
instagram_intent = Intent(tag="instagram", response=instagram_response, pattern=["Instagram", "instagram account", "instagram page"])


faq_set_intent = Intent(tag="faq_set", response=Response(response_items = [ResponseElement(type="label", element=Label(label_body="psuedo label", label_value="psuedo_label"))]), pattern=["Can we buy the products from Jaquar orientation centre?", "Where do I get Jaquar Orientation Center addresses? Or how can I locate Jaquar orientation centres?", "What is PMS and PMC?", "How to avoid slipping danger from the bathroom?", "What do you mean by Jaquar complete bathing solutions?", "Can LED lighting harm our eyesight?", "Are LED light bulbs worth the money??", "What are the best light bulbs for enclosure"])

previous_intent = Intent(tag="previous_menu", response=Response(response_items = [ResponseElement(type="label", element=Label(label_body="psuedo label", label_value="psuedo_label"))]), pattern=["previous_menu","previous menu","go back","go back to previous menu","go to previous menu"])

nsfw_response = Response(response_items = [ResponseElement(type="label", element=Label(label_body="I'm sorry that you're so upset. I am here to help you and will do my best to answer any queries, but I am unable to do so if you continue to swear.", label_value="nsfw"))])

# ## FAQs
faq1 = Label(label_body="No, one can only see the physical products. Jaquar orientation centre's are the best place to see, touch & feel the latest collections and complete range of bathing products & accessories. It also offers, Live Demo, Expert advice, Installation assistance, free estimate assistance.", label_type="default", label_value="faq1")
faq2 = Label(label_body="Plz visit our website Jaquar.com and get the addresses under 'Contact us'.", label_type="default", label_value="faq2")
faq3_1 = Label(label_body="PMS stands for “Preventive maintenance service” which is given free of cost during purchase of all Artize and Jaquar wellness products. Whereas, PMC stands for “Preventive maintenance contract” which is available at a very nominal fee and cover 4 services per year.", label_type="default", label_value="faq3")
faq3_2 = Label(label_body="For more details you can speak to our service personnel ", label_type="default", label_value="faq3")
faq3_3 = Url(url_title="1800-121-6808", url_url="tel://18001216808")
faq4 = Label(label_body="Install Jaquar ready - to -fiter enclosures that separates dry and wet areas thereby minimizing the risk of slipping & falling. It is available in standard & customized sizes.", label_type="default", label_value="faq4")
faq5 = Label(label_body="Jaquar offers a unique and comprehensive bathing portfolio of products for every kind of bath spaces. It offers complete bathing solutions to your bathroom by providing faucets, ers, sanitaryware, whirlpools, steam cabins, spas,er enclosures, water heaters, flushing system & lighting.", label_type="default", label_value="faq5")
faq6 = Label(label_body="LED lights emit a significant amount of blue light that can disrupt sleeping habits and lead to eye illness over time. LED lights do not emit near-infrared radiation, the good radiation which the sun emits.", label_type="default", label_value="faq6")
faq7_1 = Label(label_body="Yes, definitely. Here's why we say LED light bulbs are an absolute value for money. As with many other items, you get what you pay for when it comes to LED lighting.", label_type="default", label_value="faq7")
faq7_2 = Label(label_body="The quality difference might be highly evident. However, when you consider maintenance, light quality, and energy savings, an initial investment in high-quality LED lights can save you money in the long term.", label_type="default", label_value="faq7")
faq8 = Label(label_body="The latest LED enclosure lamps come with a variety of mounting options. You'll also want to ensure that they won't get in the way of routine maintenance once the lamps are in place. As a result, use lamps with a tiny footprint if at all possible.", label_type="default", label_value="faq8")

faq1_response = Response(response_items = [ResponseElement(type="label", element=faq1),  ResponseElement(type="list", element=common_list)])
faq2_response = Response(response_items = [ResponseElement(type="label", element=faq2),  ResponseElement(type="list", element=common_list)])
faq3_response = Response(response_items = [ResponseElement(type="label", element=faq3_1),ResponseElement(type="label", element=faq3_2),ResponseElement(type="url", element=faq3_3),  ResponseElement(type="list", element=common_list)])
faq4_response = Response(response_items = [ResponseElement(type="label", element=faq4),  ResponseElement(type="list", element=common_list)])
faq5_response = Response(response_items = [ResponseElement(type="label", element=faq5),  ResponseElement(type="list", element=common_list)])
faq6_response = Response(response_items = [ResponseElement(type="label", element=faq6),  ResponseElement(type="list", element=common_list)])
faq7_response = Response(response_items = [ResponseElement(type="label", element=faq7_1),ResponseElement(type="label", element=faq7_2),  ResponseElement(type="list", element=common_list)])
faq8_response = Response(response_items = [ResponseElement(type="label", element=faq8),  ResponseElement(type="list", element=common_list)])

import json
with open('jaquar_intentsss.json', 'w') as f:
    json.dump({"intents":[feedback_intent.dict(),feedback_exit_intent.dict(),welcome_intent.dict(),main_menu_intent.dict(),thankyou_intent.dict(),bot_challenge_intent.dict(),customer_intent.dict(),bathroom_products_intent.dict(),lighting_products_intent.dict(),professional_lighting_intent.dict(),consumer_lighting_intent.dict(),call_purchase_assistant_intent.dict(),other_queries_intent.dict(),faq_intent.dict(),exit_intent.dict(),after_redirect_intent.dict(),center_virtual_tour_intent.dict(),dealer_location_intent.dict(),download_customer_catalogue_intent.dict(),customer_service_intent.dict(),download_app_intent.dict(),app_store_intent.dict(),google_play_intent.dict(),social_media_intent.dict(),professional_intent.dict(),professional_service_form_intent.dict(),labour_service_form_intent.dict(),professional_service_intent.dict(),download_professional_catalogue_intent.dict(),cad_drawings_intent.dict(),product_3d_view_intent.dict(),new_arrivals_intent.dict(),labour_service_intent.dict(),installation_video_intent.dict(),catalogue_download_intent.dict(),linkedin_intent.dict(),twitter_intent.dict(),facebook_intent.dict(),youtube_intent.dict(),instagram_intent.dict(),faq_set_intent.dict(),previous_intent.dict()]}, f)

nsfw_response.dict()

faq_dict = {
        "can we buy the products from jaquar orientation centre?": faq1_response.dict(),
        "where do i get jaquar orientation center addresses? or how can i locate jaquar orientation centres?": faq2_response.dict(),
        "what is pms and pmc?": faq3_response.dict(),
        "how to avoid slipping danger from the bathroom?": faq4_response.dict(),
        "what do you mean by jaquar complete bathing solutions?": faq5_response.dict(),
        "can led lighting harm our eyesight?": faq6_response.dict(),
        "are led light bulbs worth the money??": faq7_response.dict(),
        "what are the best light bulbs for enclosures?": faq8_response.dict()
}

faq_dict = {'can we buy the products from jaquar orientation centre?': {'response_items': [{'type': 'label',
    'element': {'label_body': "No, one can only see the physical products. Jaquar orientation centre's are the best place to see, touch & feel the latest collections and complete range of bathing products & accessories. It also offers, Live Demo, Expert advice, Installation assistance, free estimate assistance.",
     'label_type': 'default',
     'label_value': 'faq1'}},
   {'type': 'list',
    'element': {'list_items': [{'button_text': 'Go back to Main Menu',
       'button_value': 'Main Menu',
       'button_type': 'default',
       'button_url_redirect': None,
       'icon_url': None},
      {'button_text': 'Exit',
       'button_value': 'Exit',
       'button_type': 'default',
       'button_url_redirect': None,
       'icon_url': None}],
     'list_value': 'social_links'}}],
  'context': None},
 'where do i get jaquar orientation center addresses? or how can i locate jaquar orientation centres?': {'response_items': [{'type': 'label',
    'element': {'label_body': "Plz visit our website Jaquar.com and get the addresses under 'Contact us'.",
     'label_type': 'default',
     'label_value': 'faq2'}},
   {'type': 'list',
    'element': {'list_items': [{'button_text': 'Go back to Main Menu',
       'button_value': 'Main Menu',
       'button_type': 'default',
       'button_url_redirect': None,
       'icon_url': None},
      {'button_text': 'Exit',
       'button_value': 'Exit',
       'button_type': 'default',
       'button_url_redirect': None,
       'icon_url': None}],
     'list_value': 'social_links'}}],
  'context': None},
 'what is pms and pmc?': {'response_items': [{'type': 'label',
    'element': {'label_body': 'PMS stands for “Preventive maintenance service” which is given free of cost during purchase of all Artize and Jaquar wellness products. Whereas, PMC stands for “Preventive maintenance contract” which is available at a very nominal fee and cover 4 services per year.',
     'label_type': 'default',
     'label_value': 'faq3'}},
   {'type': 'label',
    'element': {'label_body': 'For more details you can speak to our service personnel ',
     'label_type': 'default',
     'label_value': 'faq3'}},
   {'type': 'url',
    'element': {'url_title': '1800-121-6808',
     'url_url': 'tel://18001216808',
     'url_text': None}},
   {'type': 'list',
    'element': {'list_items': [{'button_text': 'Go back to Main Menu',
       'button_value': 'Main Menu',
       'button_type': 'default',
       'button_url_redirect': None,
       'icon_url': None},
      {'button_text': 'Exit',
       'button_value': 'Exit',
       'button_type': 'default',
       'button_url_redirect': None,
       'icon_url': None}],
     'list_value': 'social_links'}}],
  'context': None},
 'how to avoid slipping danger from the bathroom?': {'response_items': [{'type': 'label',
    'element': {'label_body': 'Install Jaquar ready - to -fiter enclosures that separates dry and wet areas thereby minimizing the risk of slipping & falling. It is available in standard & customized sizes.',
     'label_type': 'default',
     'label_value': 'faq4'}},
   {'type': 'list',
    'element': {'list_items': [{'button_text': 'Go back to Main Menu',
       'button_value': 'Main Menu',
       'button_type': 'default',
       'button_url_redirect': None,
       'icon_url': None},
      {'button_text': 'Exit',
       'button_value': 'Exit',
       'button_type': 'default',
       'button_url_redirect': None,
       'icon_url': None}],
     'list_value': 'social_links'}}],
  'context': None},
 'what do you mean by jaquar complete bathing solutions?': {'response_items': [{'type': 'label',
    'element': {'label_body': 'Jaquar offers a unique and comprehensive bathing portfolio of products for every kind of bath spaces. It offers complete bathing solutions to your bathroom by providing faucets, ers, sanitaryware, whirlpools, steam cabins, spas,er enclosures, water heaters, flushing system & lighting.',
     'label_type': 'default',
     'label_value': 'faq5'}},
   {'type': 'list',
    'element': {'list_items': [{'button_text': 'Go back to Main Menu',
       'button_value': 'Main Menu',
       'button_type': 'default',
       'button_url_redirect': None,
       'icon_url': None},
      {'button_text': 'Exit',
       'button_value': 'Exit',
       'button_type': 'default',
       'button_url_redirect': None,
       'icon_url': None}],
     'list_value': 'social_links'}}],
  'context': None},
 'can led lighting harm our eyesight?': {'response_items': [{'type': 'label',
    'element': {'label_body': 'LED lights emit a significant amount of blue light that can disrupt sleeping habits and lead to eye illness over time. LED lights do not emit near-infrared radiation, the good radiation which the sun emits.',
     'label_type': 'default',
     'label_value': 'faq6'}},
   {'type': 'list',
    'element': {'list_items': [{'button_text': 'Go back to Main Menu',
       'button_value': 'Main Menu',
       'button_type': 'default',
       'button_url_redirect': None,
       'icon_url': None},
      {'button_text': 'Exit',
       'button_value': 'Exit',
       'button_type': 'default',
       'button_url_redirect': None,
       'icon_url': None}],
     'list_value': 'social_links'}}],
  'context': None},
 'are led light bulbs worth the money??': {'response_items': [{'type': 'label',
    'element': {'label_body': "Yes, definitely. Here's why we say LED light bulbs are an absolute value for money. As with many other items, you get what you pay for when it comes to LED lighting.",
     'label_type': 'default',
     'label_value': 'faq7'}},
   {'type': 'label',
    'element': {'label_body': 'The quality difference might be highly evident. However, when you consider maintenance, light quality, and energy savings, an initial investment in high-quality LED lights can save you money in the long term.',
     'label_type': 'default',
     'label_value': 'faq7'}},
   {'type': 'list',
    'element': {'list_items': [{'button_text': 'Go back to Main Menu',
       'button_value': 'Main Menu',
       'button_type': 'default',
       'button_url_redirect': None,
       'icon_url': None},
      {'button_text': 'Exit',
       'button_value': 'Exit',
       'button_type': 'default',
       'button_url_redirect': None,
       'icon_url': None}],
     'list_value': 'social_links'}}],
  'context': None},
 'what are the best light bulbs for enclosures?': {'response_items': [{'type': 'label',
    'element': {'label_body': "The latest LED enclosure lamps come with a variety of mounting options. You'll also want to ensure that they won't get in the way of routine maintenance once the lamps are in place. As a result, use lamps with a tiny footprint if at all possible.",
     'label_type': 'default',
     'label_value': 'faq8'}},
   {'type': 'list',
    'element': {'list_items': [{'button_text': 'Go back to Main Menu',
       'button_value': 'Main Menu',
       'button_type': 'default',
       'button_url_redirect': None,
       'icon_url': None},
      {'button_text': 'Exit',
       'button_value': 'Exit',
       'button_type': 'default',
       'button_url_redirect': None,
       'icon_url': None}],
     'list_value': 'social_links'}}],
  'context': None}}



'''from google.colab import drive
drive.mount("/content/drive", force_remount=True)'''

'''import os
root_dir = "/content/drive/My Drive/"
project_folder = "Colab Notebooks/Jaquar/"
def create_and_set_working_directory(project_folder):
  if os.path.isdir(root_dir + project_folder) == False:
    os.mkdir(root_dir + project_folder)
    print(root_dir + project_folder + 'did not existed and was created.')
  os.chdir(root_dir + project_folder)
create_and_set_working_directory(project_folder)'''

#!ls

'''!pip install firebase-admin
!pip install fastapi
!pip install alt-profanity-check
!pip install sentence-transformers
!pip install intent-classifier
!pip install gibberish-detector
'''



'''firebaseConfig={
    'apiKey': "AIzaSyBCYDwcfwVZA4tJxZWyCdVEOWjxqJAv_zI",
    'authDomain': "fir-aab4b.firebaseapp.com",
    'databaseURL': "https://fir-aab4b-default-rtdb.firebaseio.com",
    'projectId': "fir-aab4b",
    'storageBucket': "fir-aab4b.appspot.com",
    'messagingSenderId': "582881782012",
    'appId': "1:582881782012:web:19b586fb32e32cbf660f79",
    'measurementId': "G-TJ6WLYRY68"
}'''
#import fcntl
#import gunicorn
#import uvicorn
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
#from fastapi.responses import JSONResponse
from pydantic import BaseModel, HttpUrl, validator
from typing import List, Optional, Union, Dict
#import requests
import json
import codecs

from profanity_check import predict_prob

from sentence_transformers import SentenceTransformer, util
from transformers import AutoTokenizer
import torch
from torch.nn.functional import softmax
from model import IntentClassifier
import time
from gibberish_detector import detector
import threading
#import os
#import firebase_admin
from firebase_admin import credentials, initialize_app, db

gibberish_detector = detector.create_from_model('big.model')
embedder = SentenceTransformer('sentence-encoder')

#Login function
cred = credentials.Certificate("fir-aab4b-firebase-adminsdk-gvvtg-848a9c84d2.json")
initialize_app(cred, {'databaseURL': 'https://fir-aab4b-default-rtdb.firebaseio.com/'})
user_c = db.reference('/User/')

corpus = ["can we buy the products from jaquar orientation centre?",
            "where do i get jaquar orientation center addresses? or how can i locate jaquar orientation centres?",
            "what is pms and pmc?",
            "how to avoid slipping danger from the bathroom?",
            "what do you mean by jaquar complete bathing solutions?",
            "can led lighting harm our eyesight?",
            "are led light bulbs worth the money??",
            "what are the best light bulbs for enclosures?"
          ]

corpus_embeddings = embedder.encode(corpus, convert_to_tensor=True)
corpus_embeddings = util.normalize_embeddings(corpus_embeddings)

intents_json = json.load(codecs.open('jaquar_intentsss.json', 'r', 'utf-8-sig'))
intents_response = { intent['tag']: intent['response'] for intent in intents_json['intents'] }

intent_tokenizer = AutoTokenizer.from_pretrained('JaquarIntentClassification')
intent_model = IntentClassifier.from_pretrained('JaquarIntentClassification')

app = FastAPI()
USERS=dict()

# Redis / Firebase

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

static_responses= {"nsfw":{'response_items': [{'type': 'label',
   'element': {'label_body': "I'm sorry that you're so upset. I am here to help you and will do my best to answer any queries, but I am unable to do so if you continue to swear.",
    'label_type': 'default', 'label_value': 'nsfw'}}], 'context': None},
 "fallback":{"response_items": [{"type": "label","element": {"label_body": "I am sorry, I don't understand", "label_type": "default", "label_value": "fallback"}}, ], "context": None}}

class MetaResponse(BaseModel):
    session_id: str
    user_response: str
    context: Optional[Dict] = None #information obtained via form ex name age email feedback query etc

def create_session(payload):
    res = user_c.child('User').set(payload)
    return res

def session_exists(session_id):
    res = user_c.child('User').child(session_id).get()   #2id
    if res:
        return True
    return False

def update_session(payload):
    if session_exists(payload['_id']):
        res = user_c.child('User').update(payload)
        return res


def check_session_status(session_id):
    init_time = USERS[session_id].init_time
    init_time = time.strptime(init_time, "%a %b %d %H:%M:%S %Y")
    session_duration = time.time() - time.mktime(init_time)
    if session_duration > 86400:
        USERS[session_id].end_time = time.asctime()
        USERS[session_id].session_status = "ended"
        update_session(USERS[session_id].to_dict())
        del USERS[session_id]


def clean_up():
    for key in USERS:
        check_session_status(key)
    time.sleep(1800)

threading.Thread(target=clean_up).start()

class SessionStack:
    def __init__(self, session_id):
        self.session_id = session_id
        self.stack = []
        self.history = []
        self.init_time = time.asctime()
        self.end_time = None
        self.context = dict() #information obtained via form ex name age email feedback query etc
        self.session_status = "active" # active , ended
        self.fallback = []

    def add(self, dataval,user_response):
        self.stack.append(dataval)
        self.history.append({'user_response':user_response,'intent':dataval})

    def peek(self):
        return self.stack[-1]

    def reset(self,reset_index):
        self.stack = self.stack[:reset_index]

    def pop(self):
        return self.stack.pop()
    
    def to_dict(self):
        return {'_id':self.session_id,'history':self.history,'init_time':self.init_time,'context':self.context,'fallback':self.fallback,'session_status':self.session_status, 'end_time':self.end_time}


    

@app.get("/")
def root():
    return "Welcome to AI-LifeBot"

def classifyIntents(text):
    with torch.no_grad():
        encoded_input = intent_tokenizer(text, return_tensors='pt')
        output = intent_model(**encoded_input)
        scores = softmax(output[0], dim=1)[0].detach().cpu().numpy()
        score = scores.max()
        intent = intent_model.config.id2label[scores.argmax()]
    return (intent,score)

def classify(sentence):
    ERROR_THRESHOLD = 0.65
    intents, score = classifyIntents(sentence)
    if score > ERROR_THRESHOLD:
        return intents
    return None

@app.post("/response")
def getResponse(payload: MetaResponse):
    session_id = payload.session_id
    user_response = payload.user_response
    context = payload.context
    
    if session_id not in USERS:
        USERS[session_id]=SessionStack(session_id=session_id)
        res = user_c.child('User').child(session_id).get()
        if res:
          USERS[session_id].context = res['context']
          USERS[session_id].history = res['history']
          USERS[session_id].fallback = res['fallback']
          USERS[session_id].session_status = res['session_status']
          USERS[session_id].end_time = res['end_time']
          USERS[session_id].init_time = res['init_time']
        else:
          res = create_session(USERS[session_id].to_dict())
    if context is not None:
        USERS[session_id].context.update(context)
    
    if float(predict_prob([user_response]))>=0.50:
        USERS[session_id].fallback.append(user_response)
        update_session(USERS[session_id].to_dict())
        return static_responses['nsfw']
    if gibberish_detector.is_gibberish(user_response) and user_response.find("faq")==-1:
        USERS[session_id].fallback.append(user_response)
        update_session(USERS[session_id].to_dict())
        return static_responses["fallback"]

    classified_intent = classify(user_response)
    if classified_intent:
        if classified_intent=="welcome":
            USERS[session_id].add('main_menu',user_response)
            update_session(USERS[session_id].to_dict())
            return intents_response[classified_intent]
        elif classified_intent == "previous_menu":
            if len(USERS[session_id].stack) > 1:
                #popped_item = USERS[session_id].pop()
                classified_intent = USERS[session_id].peek()
                if classified_intent == "faq_set":
                    classified_intent = "main_menu"
            else:
                classified_intent = "main_menu"
            return intents_response[classified_intent]
        elif classified_intent == "main_menu":
            if USERS[session_id].stack[0]=="main_menu":
                USERS[session_id].reset(1)
            else:
                USERS[session_id].add('main_menu',user_response)
            update_session(USERS[session_id].to_dict())
            return intents_response[classified_intent]
        elif classified_intent == "exit":
            USERS[session_id].add(classified_intent, user_response)
            update_session(USERS[session_id].to_dict())
            return intents_response[classified_intent]
        elif classified_intent == "faq_set":
            if user_response in faq_dict:
                USERS[session_id].add(classified_intent, user_response)
                update_session(USERS[session_id].to_dict())
                return faq_dict[user_response]
            else:
                query_embedding = embedder.encode(user_response, convert_to_tensor=True)
                query_embeddings = util.normalize_embeddings(query_embedding.unsqueeze(0))
                hits = util.semantic_search(query_embeddings, corpus_embeddings, score_function=util.dot_score, top_k=1)
                hit = hits[0][0]
                if hit['score'] > 0.50:
                    query_hit = corpus[hit['corpus_id']]
                    USERS[session_id].add(classified_intent, user_response)
                    update_session(USERS[session_id].to_dict())
                    return faq_dict[query_hit]
                else:
                    USERS[session_id].fallback.append(user_response)
                    update_session(USERS[session_id].to_dict())
                    return static_responses["fallback"]
        else:
            USERS[session_id].add(classified_intent, user_response)
            update_session(USERS[session_id].to_dict())
            return intents_response[classified_intent]
    else:
        USERS[session_id].fallback.append(user_response)
        update_session(USERS[session_id].to_dict())
        return static_responses["fallback"]

#getResponse(MetaResponse( session_id = "a79b8f7fb9b7BBHDG2b8b7", user_response = "hello".lower()))
getResponse(MetaResponse( session_id = "a79b8f7fb9b7BBHDG2b8b7", user_response = "you a bot bro?".lower(), context = {"name": "akshay", "email": "akha@gmail.com","feedback": "good"}))

#USERS["a79b8f7fb9b7BBHDG2b8b7"].stack

#USERS["a79b8f7fb9b7BBHDG2b8b7"].history

#classifyIntents("conserm lighting")

#node, pm2 npm
'''if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)'''


'''gunicorn --workers=3 test:app
use = egg:gunicorn
host = 0.0.0.0
port = 8000
workers = 3'''

#gunicorn --bind=0.0.0.0:8000 app:app 
#gunicorn --bind 0.0.0.0:8000 --workers 1 --worker-class uvicorn.workers.UvicornWorker jaquar_bot:app




